const HANDLE_CHANGE = 'HANDLE_CHANGE'
const HANDLE_SUBMIT = 'HANDLE_SUBMIT'
const TOGGLE_ERROR = 'TOGGLE_ERROR'
const TOGGLE_LOADING = 'TOGGLE_LOADING'
const SET_REQUESTS = 'SET_REQUESTS'
const SET_USER = 'SET_USER'
const SET_FOLLOWERS = 'SET_FOLLOWERS'
const SET_REPOS = 'SET_REPOS'
export {
  HANDLE_CHANGE,
  HANDLE_SUBMIT,
  TOGGLE_ERROR,
  TOGGLE_LOADING,
  SET_REQUESTS,
  SET_USER,
  SET_FOLLOWERS,
  SET_REPOS,
}